@startuml Slide2_PhasedApproach_Part1
!include gost-theme.puml

start

partition "ФАЗА 1" {
  :Детерминированные алгоритмы;
  :Анализ трендов и уставок;
  :Генерация рекомендаций;
  :Сбор статистических данных;
  :Веб-интерфейсы для пользователей;
}

:Накопление данных;

@enduml


