@startuml Slide9_Phase1_Timeline_Part1
!include gost-theme.puml

start

partition "Анализ и проектирование\n(3-5 недель)" {
  :Анализ требований;
  :Техническое проектирование;
  :Проектирование БД и API;
  :Дизайн интерфейсов;
}

partition "Разработка инфраструктуры\n(5-6 недель)" {
  :Настройка БД и инфраструктуры;
  :Разработка слоя интеграции;
  :Базовое API;
}

@enduml


