@startuml Slide9_Phase1_Timeline_Part3
!include gost-theme.puml

partition "Интеграция и тестирование\n(5-6 недель)" {
  :Интеграционное тестирование;
  :E2E тестирование;
  :Приемочное тестирование;
  :Нагрузочное тестирование;
}

partition "Пилот и развертывание\n(15-21 неделя)" {
  :Пилот на 5-10 объектах;
  :Доработка;
  :Масштабирование;
}

stop

@enduml

