@startuml Slide10_Phase2_Timeline_Overview
!include gost-theme.puml

start

:Анализ и подготовка\n(5-6 недель);
:Проектирование ML\n(3-5 недель);
:ML инфраструктура\n(5-6 недель);
:Разработка моделей\n(9-12 недель);
:Интеграция\n(5-6 недель);
:Тестирование и пилот\n(11-14 недель);

stop

@enduml

