@startuml Slide9_Phase1_Timeline_Overview
!include gost-theme.puml

start

:Анализ и проектирование\n(3-5 недель);
:Разработка инфраструктуры\n(5-6 недель);
:Разработка алгоритмов\n(6-8 недель);
:Разработка интерфейсов\n(6-8 недель);
:Интеграция и тестирование\n(5-6 недель);
:Пилот и развертывание\n(15-21 неделя);

stop

@enduml


